### ISSUE TITLE
怎么给题目指定语言呢

### ISSUE THREAD

**Issue by modcscom** [winterant/LDUOnlineJudge#17]
程序试用感觉挺好，个人觉得还能优化下这些

1、希望能增加个给编程指定语言的选项。
2、填空题指定的语言发现在前端是不起作用的，希望修改下这个bug
3、对比其他oj，题目内容在左侧，代码区放右侧感觉好些
4、如果可能，最好带一个像hustoj的露一手或者像[Hydro](https://hydro.js.org/) 这样的代码自测内容，方便新手

**Comment by modcscom** [comment]
![image](https://user-images.githubusercontent.com/59500078/173356824-509a3337-9079-40a5-9243-33857f8361b4.png)
![image](https://user-images.githubusercontent.com/59500078/173356937-613b438e-5af5-42a5-bc07-dee9f39ed112.png)

**Comment by winterant** [comment]
> 程序试用感觉挺好，个人觉得还能优化下这些
> 
> 1、希望能增加个给编程指定语言的选项。 2、填空题指定的语言发现在前端是不起作用的，希望修改下这个bug 3、对比其他oj，题目内容在左侧，代码区放右侧感觉好些 4、如果可能，最好带一个像hustoj的露一手或者像[Hydro](https://hydro.js.org/) 这样的代码自测内容，方便新手

感谢支持！感谢提出的宝贵建议！
1. 目前竞赛中可指定语言，题库中打开题目仅支持允许所有语言提交。这个想法不错，我记下开发时增加；
2. 目前填空题提交时需要手动选择语言，很不方便。后续优先处理下这个bug；
3. 这个建议很棒，类似于力扣界面；我加到开发计划中；
4. 之前有考虑到这个功能，限于时间未及时开发；很棒的建议，我的想法是与第3条建议结合，模仿力扣界面。
再次感谢你的关注和建议，期待与你更多交流~
